name = "pantrypulse"
main = "worker.js"
compatibility_date = "2025-08-07"
compatibility_flags = ["nodejs_compat"]


[site]
bucket = "./client/build"
entry-point = "."

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "56aaa06488384316b83843f6780f744d"

[vars]
# This will be overridden by the secret you set in the Cloudflare dashboard
JWT_SECRET = "a-default-secret-for-local-development"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



